FROM phpmyadmin:5.2.3

LABEL maintainer="aur3l.roman@gmail.com"
LABEL version="5.2.3"
LABEL description="phpMyAdmin for WordPress Docker-in-Docker setup"

# Add volume for sessions to allow session persistence
VOLUME /sessions

# We expose phpMyAdmin on port 80
EXPOSE 80